version: '3'
services:
  app:
    container_name: blog_sys
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    working_dir: /var/www/html
    volumes:
      - "./src/:/var/www/html"
  web:
    container_name: blog_nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 5000:5000
    working_dir: /var/www/html
    volumes:
      - "./src/:/var/www/html"
      - "./docker/nginx/conf:/etc/nginx/conf.d"
    depends_on:
      - app
      - localstack
  localstack:
    container_name: localstack
    image: localstack/localstack:0.14.4
    ports:
      - 4566:4566
    volumes:
      - 'localstack-data:/tmp/localstack'
    environment:
      - SERVICES=dynamodb
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=ap-northeast-1
      - DATA_DIR=/tmp/localstack/data
      - DISABLE_CORS_CHECKS=1
  # dynamodb-local:
  #   image: amazon/dynamodb-local
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - "./localstack-data:/data"
  #   command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "/data"]
  dynamodb-admin:
    container_name: dynamodb_admin
    image: aaronshaf/dynamodb-admin:latest
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=localstack:4566
      - AWS_REGION=ap-northeast-1
    depends_on:
      - localstack
volumes:
  localstack-data:
    driver: local